CREATE DATABASE ASSIGNMET1;

CREATE TABLE STUDENT.STUDENT(STUDENT_ID INT PRIMARY KEY,STUDENT_NAME VARCHAR(30) NOT NULL,
STUDENT_AGE INT CHECK(STUDENT_AGE >= 18),STUDENT_ADDRESS VARCHAR(40));

SELECT * FROM STUDENT.STUDENT;

INSERT INTO STUDENT.STUDENT(STUDENT_ID,STUDENT_NAME,STUDENT_AGE,STUDENT_ADDRESS)
VALUES(102,'JOHN',20,'MYSURU'),
(103,'SMITH',22,'BENGLORE'),
(104,'JENNY',23,'MANDYA');

INSERT INTO STUDENT.STUDENT VALUES(105,'ALIEXA',12,'MANDYA');

CREATE TABLE SALES.SALES(SALESID INT PRIMARY KEY ,
CUSTOMER_ID INT,
CUSTOMER_NAME VARCHAR(50),
LOCATION VARCHAR(60),
COMMISSION DECIMAL(10,2),
TOTALSALES DECIMAL(10,2),
CONSTRAINT CHK_COMMISSION CHECK( (Location = 'LONDON' AND Commission > 1000) OR  (Location = 'US' AND Commission < 1000))
);

INSERT INTO SALES.SALES(SALESID,CUSTOMER_ID,CUSTOMER_NAME,LOCATION,COMMISSION,TOTALSALES)VALUES
(4,1004,'SMITH','US',500.00,800.00);

SELECT * FROM SALES.SALES;

